name: Docker Image CI

on:
  push:
    branches: [ "master", "dev"]
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

  schedule:
    # Runs "At 10:30 UTC on Thursday" (see https://crontab.guru)
    - cron: '30 10 * * 4'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: docker
    steps:
    - uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker images
      env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_REPOSITORY: mjakubietest
      run: ./scripts/ci.sh
      shell: bash
